baseurl = "https://merkleblock.com/"
languageCode = "en-us"
title = "MerkleBlock LLP"
theme = "creative"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Merkleblock Solutions"
	description = "Blockchain Consultancy, Bitcoin, Blockchain Development, Decentralized, P2P, Altcoin, CryptoCurrency"

	# The path must be relative to the static folder
	favicon = "favicon.ico"
	logo = "img/logo.png"


	# Navigation
	[params.navigation]
		brand = "MerkleBlock LLP"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "MerkleBlock LLP"
		subtitle   = "MerkleBlock LLP is a research and development studio focusing on innovative solutions based on the blockchain"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "About us"
		description = "We are a small group of developers who are passionate about distributed systems. We love building cutting edge products which harness the power of the blockchain. If you are looking for a reliable team to support your development, we can help."


	# Service section
	[params.services]
		headline = "Our Services"

        [[params.services.list]]
            icon = "fa-bitcoin"
            title = "Bitcoin"
            description = "We provide technical expertise in bitcoin and cryptocurrencies."

        [[params.services.list]]
			icon = "fa-rocket"
			title = "Development"
			description = "We develop applications and services built on the blockchain."

		[[params.services.list]]
            icon = "fa-user-secret"
            title = "Security"
            description = "We provide security and privacy solutions based on industry-wide best practices."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "View our code"

		[params.aside.button]
			text = "Github"
			link = "https://github.com/merkleblock"

	# Contact section
	[params.contact]
		headline = "Contact us"
		description = "Get in touch!"
		skype = "merkleblock"
		email = "contact@merkleblock.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
